// File auto-generated by ExposerGenerator.
using System.Reflection;
using UnityEngine;

namespace NGTools.NGRemoteScene
{
	internal sealed class TransformExposer : ComponentExposer
	{
		public	TransformExposer() : base(typeof(Transform))
		{
		}

		public override PropertyInfo[]	GetPropertyInfos()
		{
			return new PropertyInfo[] {
#if UNITY_4_5 || UNITY_4_6 || UNITY_4_7 || UNITY_5_0 || UNITY_5_1 || UNITY_5_2 || UNITY_5_3 || UNITY_5_4 || UNITY_5_5 || UNITY_5_6 || UNITY_5_6_OR_NEWER
				this.type.GetProperty("localPosition"),
#endif
#if UNITY_4_5 || UNITY_4_6 || UNITY_4_7 || UNITY_5_0 || UNITY_5_1 || UNITY_5_2 || UNITY_5_3 || UNITY_5_4 || UNITY_5_5 || UNITY_5_6 || UNITY_5_6_OR_NEWER
				this.type.GetProperty("localEulerAngles"),
#endif
#if UNITY_4_5 || UNITY_4_6 || UNITY_4_7 || UNITY_5_0 || UNITY_5_1 || UNITY_5_2 || UNITY_5_3 || UNITY_5_4 || UNITY_5_5 || UNITY_5_6 || UNITY_5_6_OR_NEWER
				this.type.GetProperty("localScale"),
#endif
			};
		}
	}
}