##
## Makefile for  in /home/haddad_b//LangageC/BLooDBuRNiNG
## 
## Made by benjamin haddad
## Login   <haddad_b@epitech.net>
## 
## Started on  Tue Jan 15 17:16:24 2013 benjamin haddad
## Last update Tue Jan 15 17:17:31 2013 benjamin haddad
##

NAME = §

all:
	 rm -f *# rm -f *~
